version: '3.8'

x-dev-base: &dev-base
  volumes: 
    - .:/home/node/app
    - node-modules:/home/node/app/node_modules
    - dist:/home/node/app/dist
  working_dir: /home/node/app
  init: true
  environment:
    - TZ=Asia/Tokyo
  
  
volumes: 
  node-modules:
  dist:

services: 
  builder:
    << : *dev-base
    build: 
      context: .
      dockerfile: ./Dockerfile
      target: builder

  shell:
    << : *dev-base
    build: 
      context: .
      dockerfile: ./Dockerfile
      target: shell
    tty: true
